SSAnne_2F_Corridor_Text_ThisShipIsLuxuryLiner::
    .string "This ship, she is a luxury liner for\n"
    .string "TRAINERS of the world!\p"
    .string "At every port, we hold parties with\n"
    .string "invited TRAINERS.$"

SSAnne_2F_Corridor_Text_RivalIntro::
    .string "{RIVAL}: Bonjour!\n"
    .string "{PLAYER}!\p"
    .string "Imagine seeing you here!\n"
    .string "{PLAYER}, were you really invited?\p"
    .string "So how's your POKéDEX coming?\p"
    .string "I already caught 40 kinds, pal.\n"
    .string "Different kinds are everywhere.\p"
    .string "Crawl around in grassy areas, and\n"
    .string "look hard for them.$"

SSAnne_2F_Corridor_Text_RivalDefeat::
    .string "Humph!\p"
    .string "At least you're raising your\n"
    .string "POKéMON!$"

SSAnne_2F_Corridor_Text_RivalVictory::
    .string "{PLAYER}‥！\n"
    .string "ふなよい　してるのか！\p"
    .string "もっと　からだ\n"
    .string "きたえた　ほうが　いいぜ！$"

SSAnne_2F_Corridor_Text_RivalPostBattle::
    .string "{RIVAL}: I heard there was a CUT\n"
    .string "master on board.\p"
    .string "But he was just a seasick old man!\p"
    .string "CUT itself is really useful.\n"
    .string "Yup, it'll be handy.\p"
    .string "You should go see him, too.\n"
    .string "Smell ya!$"

SSAnne_2F_Corridor_Text_RivalPostBattleWithArbokPart1::
    .string "{RIVAL}: Beau combat mec... hé\n"
    .string "mais attend... Ce POKéMON\p"
    .string "... Non, je ne rêve pas, c'est\n"
    .string "un ARBOK?! Wow, {PLAYER}...\p"
    .string "Je t'ai toujours méprisé, mais\n"
    .string "là tu m'impressionne de dingue!\p"
    .string "Un ARBOK sur le bateau? C'est\n"
    .string "le truc le plus cool que j'ai\p"
    .string "jamais vu de ma putain de life man!\n"
    .string "Tout comme Harry qui devient le\p"
    .string "meilleur ami de son oncle car il\n"
    .string "devine pourquoi il n'aime pas le\p"
    .string "dimanche, tu passes subitement de mon\n"
    .string "ennemi juré à mon meilleur ami! T'es\p"
    .string "tellement cool mec, je suis\n"
    .string "ultra fan de toi maintenant!\p"
    .string "A tel point que je t'offre tout ça:\n"
    .string "Tiens, mon meilleur ami!$"

SSAnne_2F_Corridor_Text_RivalPostBattleWithArbokPart2::
    .string "{RIVAL}: Ca t'épate, pas vrai?\n"
    .string "Eh oui, puisque tu m'a impressionné\p"
    .string "avec ton ARBOK sur le bateau, je\n"
    .string "t'offre 50 MASTER BALL! Héhéhé...\p"
    .string "Le professeur chen me les a donné,\n"
    .string "non pas parce que je suis le meilleur\p"
    .string "mais parce que c'est mon grand père. Mais,\n"
    .string "il est évident que tu les mérites\p"
    .string "1000 fois plus que moi, vu que\n"
    .string "tu es cool au point d'emmener\p"
    .string "un ARBOK sur le bateau.\n"
    .string "Allez, ciao mon dieu vivant!$"

SSAnne_2F_Corridor_Text_ReceivedFiftyMasterBall::
    .string "{PLAYER} received 50 MASTER BALLS.$"
